### ISSUE TITLE
Create all different task types

### ISSUE THREAD

**Issue by deltango** [CS2103JAN2017-W13-B1/main#21]
uTask should be able to create the 3 different types of tasks:
1. `Event` task (include start and end time stamp)
2. `Deadline` task (only include end date)
3. `Floating` task (without start nor end timing)

These attributes are shared across all task: 

1. Name
2. Frequency (for recurring task)
3. Tag(s)
4. Completed

**Comment by yong24s** [comment]
![floating task with all](https://cloud.githubusercontent.com/assets/2003406/23842952/501b2dce-07f3-11e7-8399-72d169a86983.JPG)
![deadline only](https://cloud.githubusercontent.com/assets/2003406/23842953/501b3ada-07f3-11e7-98de-b3ab645828c5.JPG)
![floating task only](https://cloud.githubusercontent.com/assets/2003406/23842956/501b5880-07f3-11e7-8de5-c748b0a38670.JPG)
![eventtask only](https://cloud.githubusercontent.com/assets/2003406/23842955/501b4fac-07f3-11e7-9a32-2b8fb46ddcd1.JPG)
![eventtask with all](https://cloud.githubusercontent.com/assets/2003406/23842954/501b4ac0-07f3-11e7-9c19-391b0151c33e.JPG)
![floating task with tags only](https://cloud.githubusercontent.com/assets/2003406/23842957/501cde4e-07f3-11e7-9681-a4623a295d41.JPG)
