### ISSUE TITLE
Retrieve task from existing file information

### ISSUE THREAD

**Issue by deltango** [CS2103JAN2017-W13-B1/main#24]
uTask should be able to retrieve task through searching by:

1. `No attributes` -> Listing all tasks
2. `Name`
3. `Deadline` or (`start_time` and `end_time`)
4. `Frequency`
5. `Tags`
6. `Completed`

**Comment by LIUJIAHAOCS** [comment]
1. No attributes: list
2. Name: find by task name
3. Time: find by time
4. Frequency: find by frequency
5. Tags: find by tags
