### ISSUE TITLE
Ensure UI is hooked with the CRUD functions of Task

### ISSUE THREAD

**Issue by deltango** [CS2103JAN2017-W13-B1/main#25]
uTask should be able to have a dynamic **user interface** that is able to provide `feedback` to the user when running the 4 essential functions:

1. Create
2. Retrieve
3. Update
4. Delete

**Comment by LIUJIAHAOCS** [comment]
1.Create is done
4.Delete is done

**Comment by LIUJIAHAOCS** [comment]
3. Retrieve is done #24
