### ISSUE TITLE
Confirm create task format 

### ISSUE THREAD

**Issue by LIUJIAHAOCS** [CS2103JAN2017-W13-B1/main#29]
Due to change of regex, the timestamp for the tasks must be in the format: from HHMM to HHMM, which lead to the problem when user try to create a task.
The command user needs to enter is: create read essay /by 200217 /from from 1830 to 2030 /repeat Every Monday /tag urgent /tag assignment.
Notice that there are two from that user need to input which is not user-friendly. we need to redesign this part to make it better.

**Comment by LIUJIAHAOCS** [comment]
Please take note that now you need to input: create Read essay /by 200217 /from from 1830 to 2030 /repeat Every Monday /tag urgent /tag assignment. when you test create-task function manually due to the recent change on regex.

**Comment by yong24s** [comment]
Noted! This also raises another issue, which is the need to verify test cases coverage.

We are currently passing all the checks and this is not detected :(
