### ISSUE TITLE
Documentation - update About Us page

### ISSUE THREAD

**Issue by LIUJIAHAOCS** [CS2103JAN2017-W13-B1/main#5]

**Comment by LIUJIAHAOCS** [comment]
![img_0320](https://cloud.githubusercontent.com/assets/14244291/23691816/de729f86-0405-11e7-9d0b-ce167d69e31a.JPG)

**Comment by LIUJIAHAOCS** [comment]
![400x514](https://cloud.githubusercontent.com/assets/14244291/23696671/90c0d61c-041f-11e7-8a84-d1a7f3505dc1.jpg)

**Comment by deltango** [comment]
![resume_photo2](https://cloud.githubusercontent.com/assets/13159718/23696845/67e94804-0420-11e7-8de2-30d1c272ebd3.png)

**Comment by deltango** [comment]
Page updated. Closing.
