### ISSUE TITLE
[DogFooding] Some places need to be improved

### ISSUE THREAD

**Issue by LIUJIAHAOCS** [CS2103JAN2017-W13-B1/main#88]
1. ~~Autofocus on the command line when open the app (now need to click on it to focus)~~ Done: Yong Hao
2. ~~Display is not user-friendly, still developer mode (270317? should be 27.Mar.2017)~~ Done: Jiahao
3. ~~now the tag color is changing everything refreshes the list (add/delete/update and so on)~~ Done: Denver

**Comment by yong24s** [comment]
~~4. Command tag parser does not detect duplicate tags.~~ Not critical

Without warning or feedback, it merge multiple entries as one


create apple /tag one /tag one /tag one
update 1 /tag one /tag one /tag one

**Comment by yong24s** [comment]
5. ~~More suggestions!~~ Done: Yong Hao

**Comment by deltango** [comment]
~~6. Undo and Redo Command doesn't work on update on same Task type. Because update will replace edited fields of original task, if the resulting task is the same as the original task.~~ Done: Denver

**Comment by deltango** [comment]
7- ~~done / undone cannot~~ Done: Denver
+ fix logic

8- ~~update tag  remove tag will remove repeat ~~
+ fix logic~~ Done: Denver

9- ~~search hidden feature~~ Done: Yong Hao
+ ~~remove search~~

10- ~~panel on find is view only for now~~
+ implement state to work on pop up panel ~~ Done: Yong Hao

11- ~~undo redo best work on changing task type~~ Done Denver, Yong Hao
+ delete okay
+ create okay
+ update on mutations
- clear cannot
- select cannot
